# Generated by Django 5.2.4 on 2025-07-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_pagevisit_subdomain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagevisit",
            name="subdomain",
        ),
    ]
